import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProviders } from "@/store/reduxProvider";
import Navbar1 from "@/components/navbar/Navbar1";
import Navbar2 from "@/components/navbar/Navbar2";
import Navbar3 from "@/components/navbar/navbar3";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProviders>
      <html lang="en" className="flex flex-col justify-between">
        <body className={inter.className}>
          <header>
            <Navbar1 />
            <Navbar2 />
          </header>
           <div className=""> {children}</div>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </ReduxProviders>
  );
}
